with 

source as (

    select * from {{ source('DBT', 'Main') }}

),

stg_unnested as (

    select
        tax_shipping,
        cancelled_at,
        cancel_reason,
        fulfillment_status,
        user_id,
        note,
        merchant_business_entity_id,
        duties_included,
        --shipping_lines,
        --shipping_address,
        --line_items,
        --fulfillments,
        customer_locale,
        payment_details,
        --discount_applications,
        --total_cash_rounding_payment_adjustment_set,
        --billing_address,
        --total_cash_rounding_refund_adjustment_set,
        --total_tax_set,
        --total_discounts_set,
        --tax_lines,
        --subtotal_price_set,
        --total_line_items_price_set,
        --discount_codes,
        --current_total_tax_set,
        --customer,
        --current_total_price_set,
        --current_total_discounts_set,
        --client_details,
        _daton_user_id,
        total_price,
        total_outstanding,
        admin_graphql_api_id,
        email,
        total_discounts,
        name,
        subtotal_price,
        current_total_discounts,
        tags,
        --refunds,
        total_price_usd,
        checkout_id,
        source_identifier,
        referring_site,
        --total_price_set,
        processed_at,
        reference,
        processing_method,
        closed_at,
        --current_subtotal_price_set,
        total_line_items_price,
        --total_shipping_price_set,
        phone,
        total_tax,
        payment_gateway_names,
        order_status_url,
        order_number,
        _daton_batch_runtime,
        taxes_included,
        tax_exempt,
        landing_site_ref,
        number,
        _daton_batch_id,
        gateway,
        financial_status,
        updated_at,
        estimated_taxes,
        contact_email,
        landing_site,
        token,
        location_id,
        current_total_price,
        cart_token,
        total_weight,
        current_total_tax,
        currency,
        created_at,
        test,
        confirmed,
        source_name,
        presentment_currency,
        browser_ip,
        id,
        confirmation_number,
        --note_attributes,
        total_tip_received,
        buyer_accepts_marketing,
        current_subtotal_price,
        app_id,
        checkout_token

    from source

)

select * from stg_unnested